# Generated by Django 4.0.6 on 2022-07-10 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='signupdate',
            field=models.DateField(default=datetime.date(2022, 7, 9), verbose_name='Sign Up Date'),
        ),
    ]
