# Generated by Django 4.0.6 on 2022-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_appointmentteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
