# Generated by Django 4.0.6 on 2022-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentteacher',
            old_name='Appointment',
            new_name='appointment',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
