# Generated by Django 4.0.6 on 2022-07-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_rename_appointment_appointmentteacher_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentTeacher',
        ),
    ]
