# Generated by Django 4.0.6 on 2022-07-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_remove_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='AppointmentInstance',
        ),
    ]
